import React from "react";
import './HomeChoose.css';
import BusinessCenterIcon from '@mui/icons-material/BusinessCenter';
import TrendingUpIcon from '@mui/icons-material/TrendingUp';
import AdjustIcon from '@mui/icons-material/Adjust';
import SupportAgentIcon from '@mui/icons-material/SupportAgent';
import InsightsIcon from '@mui/icons-material/Insights';
import VerifiedUserIcon from '@mui/icons-material/VerifiedUser'; // New Icon for added content

const reasons = [
  {
    title: "Integrated Solutions",
    description: "Focuses on lead generation and ensuring that leads generated by marketing efforts are converted into sales.",
    icon: <AdjustIcon className="icon" />,
  },
  {
    title: "Measurable Results",
    description: "Strategies that ensure growth and tangible results.",
    icon: <TrendingUpIcon className="icon" />,
  },
  {
    title: "Industry Expertise",
    description: "Deep knowledge of B2B markets to meet business goals.",
    icon: <BusinessCenterIcon className="icon" />,
  },
  {
    title: "Rapid Sales Assistance",
    description: "Dedicated support to the sales team for solving work-related queries at earliest ",
    icon: <SupportAgentIcon className="icon" />,
  },
  {
    title: "Actionable Insights",
    description: "We offer valuable insights based on data to make informed decisions for your business.",
    icon: <InsightsIcon className="icon" />,
  },
  {
    title: "Proven Track Record",
    description: "Trusted by hundreds of businesses, our proven track record ensures you’re in safe hands.",
    icon: <VerifiedUserIcon className="icon" />,
  },
];

const WhyChooseSalesyllabus2 = () => {
  return (
    <div className="why-choose-wrapper">
      <h2 className="why-choose-title">Why Partner with Us?</h2>
      <div className="why-choose-cards">
        {reasons.map((reason, index) => (
          <div key={index} className="why-choose-card">
            <div className="card-icon">{reason.icon}</div>
            <h3 className="card-title">{reason.title}</h3>
            <p className="card-description">{reason.description}</p>
          </div>
        ))}
      </div>
    </div>
  );
};

export default WhyChooseSalesyllabus2;
